version: '3'
services:
  tf:
    build: ./
    image: contino/terraform
    volumes:
      - type: bind
        source: .
        target: /opt/app
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    working_dir: /opt/app
    env_file: .env
