name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'docker-compose.yml'
      - 'Makefile'
      - '.github/workflows/**'
      - '*dockerfile'
      - 'weather-app/**'
      - 'scripts/*.sh'
      - '.env'

jobs:
  build_and_push:
    environment:
      name: approval
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Build & Push
      run: make run_build_and_push
